"""Add an bio and proifile_pic  column

Revision ID: 575399d44c04
Revises: 77e1abbaf640
Create Date: 2018-07-25 15:42:01.446023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '575399d44c04'
down_revision = '77e1abbaf640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
